### ISSUE TITLE
about panel.html

### ISSUE THREAD

**Issue by jiangyanjavawin** [SeaRhyme7th/SketchAPP#2]
Thank you for your code. when I run your code,I have a question,I can't jump to the panel. html ,and I don't known why?Do you have any idea to solve it? thank you !

**Comment by jjkislele** [comment]
Curiously, the application seems to run properly.  According to the description, perhaps there's a problem during uploading the input sketch. So please give me some hints, e.g. which line you have modified, the error code or debugging information.

**Comment by jiangyanjavawin** [comment]
Thanks for your reply,I download the project,and modified anything,and have any error information,I just put the database and .pth into floder .

**Comment by jjkislele** [comment]
老哥，咱们还是用中文吧。我下载代码然后运行是没问题的。你就是CSDN给我留言的那位吧，看截图你输出的结果是用的三维图形检索的那个数据集吧，应该是改了代码的，我猜是因为数据集的路径出问题了，预期行为是：在canvas.html绘制草图后，会跳转到panel.html，按你的描述是无法跳转的，那么应该就是那儿出问题了。

**Comment by jiangyanjavawin** [comment]
我首先下载了您的代码，没改任何地方，就是把该放的数据集放在了对应的地方，运行后就无法翻页，您的回复我看到了，我再看看路径的地方，万分感谢您能给我指出错误的地方，感谢。
